project:
  type: website

website:
  title: "Navya Sai Sadu"
  navbar:
    logo: "./images/logofinal.png"
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: projects.qmd
        text: Projects
      - href: micro-post.qmd
        text: Micro-Post

format:
  html:
    theme:  pastel-theme.scss
    css: styles.css
    toc: true
    page-layout: article
    smooth-scroll: true



